version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t myapp .
      - run:
          name: Test Docker image
          command: |
            docker run -d -p 8080:8080 --name myapp myapp
            sleep 10
            curl --retry 10 --retry-delay 5 -v http://localhost:3000
workflows:
  version: 2
  build_and_test:
    jobs:
      - build